import 'package:hookah_menu/models/flavor_model.dart';

final List<FlavorModel> flavorMixes = [
  FlavorModel(
    id: "erics_mango",
    name: "Eric's Mango",
    description:
        "Mango, aşırı yapay ya da “şekerli mangolu” değil; olgun, tatlı-ekşi, sulu ve doğal bir mango profiline sahip ve hafif çiçeksi bir dokunuş barındırıyor.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Tangiers",
    intensity: 4.0,
    price: 150,
    flavorNotes: ["Doğal Mango", "Dengeli Tatlılık", "Hafif Çiçeksi"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "orange_team",
    name: "Orange Team",
    description:
        "Tatlı-ekşi dengesiyle öne çıkan bu aroma, taze sıkılmış narenciye hissi sunar ve koyu Burley tabanı sayesinde hafif nikotin vuruşu ile dengeli bir içim sağlar",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "MustHave",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Tatlı Portakal", "Tatlı-Ekşi Narenciye", "Mandalina Kabuğu"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "sweet_peach",
    name: "Sweet Peach",
    description:
        "Her nefeste bal-şurup benzeri tatlılık ve gerçekçi şeftali aroması hissedilir. Yoğun ama dengeli bir duman sunar ve hem tek başına hem karışımlarda keyifle kullanılabilir.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "MustHave",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Doğal Tatlılık", "Hafif Bal Nüansı", "Yumuşak"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "turbo_tea",
    name: "Turbo Tea",
    description:
        "Ferahlatıcı şeftalili buzlu çay aroması ile, Hindistan’a özgü baharatlara sahip sıcak bir dönüş (twist) sunan bir karışımdır.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Darkside",
    intensity: 5.0,
    price: 200,
    flavorNotes: [
      "Hint Baharatları",
      "Soğuk Şeftali Çayı",
      "Ferah/Serinleşen Bitiş",
    ],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "ananas_shock",
    name: "Ananas Shock",
    description:
        "Doğal meyve asiditesiyle ferah, hafif “elektrikli” bir his bırakır ve BlackBurn’e özgü yüksek nikotin gücü sayesinde güçlü, tok bir içim sağlar. Tek başına karakterli bir deneyim sunarken, fresh ve mentollü karışımlarda da etkisini artıran dinamik bir profildir.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Blackburn",
    intensity: 6.0,
    price: 200,
    flavorNotes: [
      "Tatlı-Ekşi Tropikal Tat",
      "Hafif Asidik",
      "Keskin ve Ferah Bitiş",
    ],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "brazilian_tea",
    name: "Brazilian Tea",
    description:
        "Taze sıkılmış lime aromalı yeşil çay hissi veren bir nargile tütünüdür. Arka planda hafif bir asidiklik ve otumsu tat barındırır. Hem tek başına hem de karışımlarda dengeli bir içim sunar.",
    category: "Meyveli",
    tobaccoType: "Spectrum",
    brand: "Spectrum",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Ferahlatıcı Lime Çayı", "Hafif Asidik", "Orta Tatlılık"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "lemon_blast",
    name: "Lemon Blast",
    description:
        "Canlı limon aroması ile ferah ve keskin bir içim sunan Darkside tütünü. Hafif tatlılık ve dengeli asidik tonlar, nargile deneyimini taze ve enerjik hale getirir.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Darkside",
    intensity: 6.0,
    price: 200,
    flavorNotes: ["Ferah Limon", "Hafif Tatlılık", "Dengeli Asidik Ton"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "moon_peach",
    name: "Moon Peach",
    description:
        "Olgun ve tatlı şeftali aromasıyla yumuşak ve sulu bir içim sunan Satyr Moon tütünü. Doğal meyve tatları, dengeli tatlılık ve ferahlatıcı bir deneyim sağlar.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Satyr",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Olgun Şeftali", "Dengeli Tatlılık", "Sulu Aroma"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "creamy_waffle",
    name: "Creamy Waffle",
    description:
        "Tatlı ve kremamsı waffle aromasıyla keyifli bir içim sunan Kraken tütünü. Sıcak tatlı notaları ve yoğun aroma dengesi ile tatlı severler için ideal.",
    category: "Pastane",
    tobaccoType: "Cigar",
    brand: "Kraken",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Kremamsı Waffle", "Tatlı", "Yoğun Aroma"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "brownie",
    name: "Brownie",
    description:
        "Zengin çikolata ve kek aromasıyla tatlı ve yoğun bir nargile deneyimi sunan Bonche tütünü. Yoğun kakao ve şeker dengesi ile çikolata tutkunları için ideal.",
    category: "Pastane",
    tobaccoType: "Cigar",
    brand: "Bonche",
    intensity: 8.0,
    price: 200,
    flavorNotes: ["Çikolata", "Kek", "Tatlı Yoğun Aroma"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "deep_blue_sea",
    name: "Deep Blue Sea",
    description:
        "Ferahlık ve deniz esintisi hissi veren mavi meyve karışımıyla Darkside tütünü. Hafif tatlı ve ferahlatıcı aromasıyla serinletici bir nargile deneyimi sunar.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Darkside",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Mavi Meyve", "Ferah", "Hafif Tatlı"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "monkey_nuts",
    name: "Monkey Nuts",
    description:
        "Tatlı ve tuzlu fıstık aromalarıyla Mattpear tütünü. Karamelize ve kremamsı notalar ile dengeli ve keyifli bir içim sağlar.",
    category: "Pastane",
    tobaccoType: "Dark",
    brand: "Mattpear",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Fıstık", "Karamel", "Kremamsı"],
    amount: 500,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "pineapple_mango",
    name: "Pineapple Mango",
    description:
        "Taze ananas ve olgun mango aromalarının birleşimiyle ferah ve tropikal bir içim sunan Deus tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Deus",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Taze Ananas", "Olgun Mango", "Tatlı ve Sulu Tropikal Aroma"],
    amount: 40,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "passion_plum",
    name: "Passion Plum",
    description:
        "Ekşi ve tatlı erik aromasıyla ferah bir tropikal içim sunan MustHave tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "MustHave",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Tatlı Erik", "Ekşi ve Ferah", "Tropikal Karışım"],
    amount: 20,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "brazilian_tea_2",
    name: "Brazilian Tea",
    description:
        "Taze lime aromalı yeşil çay tadı veren Spectrum tütünü, hafif asidik ve otumsu notalar içerir.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Spectrum",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Ferah Lime Çayı", "Hafif Asidik", "Otumsu Bitkisel Tat"],
    amount: 10,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "tropic_juice",
    name: "Tropic Juice",
    description:
        "Tropikal meyve karışımı ile tatlı ve sulu bir içim sunan MustHave tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "MustHave",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Mango", "Ananas", "Tropikal Karışım", "Tatlı ve Ferah"],
    amount: 20,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "strawberry",
    name: "Strawberry",
    description:
        "Olgun çilek aromasıyla tatlı ve sulu bir içim sunan Deus tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Deus",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Olgun Çilek", "Tatlı ve Sulu", "Ferahlatıcı"],
    amount: 10,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "browni",
    name: "Browni",
    description:
        "Zengin çikolata ve kek aromasıyla tatlı ve yoğun bir içim sunan Satyr tütünü. Kakao ve şeker dengesi ile tatlı severler için ideal.",
    category: "Pastane",
    tobaccoType: "Dark",
    brand: "Satyr",
    intensity: 8.0,
    price: 200,
    flavorNotes: ["Çikolata", "Kek", "Yoğun Tatlı Aroma"],
    amount: 125,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "lemon_pie",
    name: "Lemon Pie",
    description:
        "Taze limon ve kremalı tart aromasıyla ferah ve tatlı bir nargile deneyimi sunan MustHave tütünü.",
    category: "Pastane",
    tobaccoType: "Dark",
    brand: "MustHave",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Limon", "Kremalı Tart", "Tatlı ve Ferah"],
    amount: 125,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "lemon",
    name: "Lemon",
    description:
        "Canlı limon aroması ile ferah ve keskin bir içim sunan Bonche tütünü.",
    category: "Pastane",
    tobaccoType: "Dark",
    brand: "Bonche",
    intensity: 7.0,
    price: 200,
    flavorNotes: ["Canlı Limon", "Hafif Tatlılık", "Keskin ve Ferah"],
    amount: 125,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "passion_fruits",
    name: "Passion Fruits",
    description:
        "Taze ve ekşi-püre aromalı passion fruit (çarkıfelek meyvesi) ile tropikal ve ferah bir içim sunan Bonche tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Bonche",
    intensity: 5.0,
    price: 200,
    flavorNotes: [
      "Taze Passion Fruit",
      "Ekşi ve Tatlı Dengesi",
      "Tropikal Ferahlatıcı Aroma",
    ],
    amount: 125,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "jungle_mix",
    name: "Jungle Mix",
    description:
        "Tropikal meyvelerin ve egzotik aromaların karışımıyla ferah ve tatlı bir içim sunan Spectrum tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Spectrum",
    intensity: 5.0,
    price: 200,
    flavorNotes: [
      "Tropikal Meyveler",
      "Egzotik Karışım",
      "Tatlı ve Ferahlatıcı Aroma",
    ],
    amount: 30,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "supernova",
    name: "Supernova",
    description:
        "Çeşitli meyve aromalarının patlayıcı bir kombinasyonu ile yoğun ve ferah bir nargile deneyimi sunan Darkside tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Darkside",
    intensity: 6.0,
    price: 200,
    flavorNotes: ["Çeşitli Meyveler", "Patlayıcı Aroma", "Yoğun ve Ferah"],
    amount: 10,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "citrus_mix",
    name: "Citrus Mix",
    description:
        "Olgun ve güneşli narenciye meyvelerinin tatlı-ekşi dengeli aromasıyla; zarif bir ferahlık ve hoş bir asidite sunan Spectrum tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Spectrum",
    intensity: 4.0,
    price: 200,
    flavorNotes: ["Olgun Narenciye", "Tatlı-Ekşi Asidite", "Ferahlık"],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "kashmir_black",
    name: "Kashmir Black",
    description:
        "Yaban böğürtleni ve Kaşmir’e özgü baharatların karışımıyla zengin, baharatlı ve meyvemsi bir nargile deneyimi sunan Tangiers Noir tütünü.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "Tangiers",
    intensity: 6.0,
    price: 200,
    flavorNotes: [
      "Böğürtlen",
      "Kaşmir Baharatı",
      "Tatlı-Ekşi Meyve",
      "Sıcak Baharatlı Bitiş",
    ],
    amount: 250,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "pinkman",
    name: "Pinkman",
    description:
        "Grapefruit, çilek ve frambuaz karışımı ile ferahlatıcı serinlik sunan MustHave tütünü; canlı ve dengeli meyve profiliyle öne çıkar.",
    category: "Meyveli",
    tobaccoType: "Dark",
    brand: "MustHave",
    intensity: 5.0,
    price: 200,
    flavorNotes: ["Grapefruit", "Çilek", "Frambuaz", "Soğuk Ferahlık"],
    amount: 125,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "brownie_blackburn",
    name: "Brownie",
    description:
        "Zengin çikolata, vanilya ve tarçın aromalarına sahip tatlı bir brownie tütünü. Yoğun tatlılığı ve sıcak “fırından çıkmış kek” hissiyle tatlı severler için ideal.",
    category: "Pastane",
    tobaccoType: "Dark",
    brand: "Blackburn",
    intensity: 6.0,
    price: 200,
    flavorNotes: ["Çikolata", "Vanilya", "Tarçın", "Yoğun Tatlı Kek Hissi"],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "dejavu",
    name: "Dejavu",
    description:
        "Ferahlatıcı kavun ve karpuz aromalarının vanilya ve mentol dokunuşlarıyla birleştiği hafif ve keyifli bir blonde tütün deneyimi.",
    category: "Meyveli",
    tobaccoType: "Blonde",
    brand: "Jibiar",
    intensity: 3.0,
    price: 200,
    flavorNotes: ["Kavun", "Karpuz", "Mentol"],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "enjoy",
    name: "Enjoy",
    description:
        "Tropikal kavun ve olgun meyvelerin nane dokunuşuyla buluştuğu, tatlı‑ferah bir blonde tütün aroması.",
    category: "Meyveli",
    tobaccoType: "Blonde",
    brand: "Jibiar",
    intensity: 3.0,
    price: 200,
    flavorNotes: ["Kavun", "Mango", "Mentol", "Üzüm", "Passion Fruit"],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "turkishmastic",
    name: "Turkish Mastic",
    description:
        "Doğal mastic reçinesinin çam‑sedirimsi ağaçsı tatları ile tatlı‑ferah bir sakız hissini birleştiren dengeli ve klasik bir aroma.",
    category: "Meyveli",
    tobaccoType: "Blonde",
    brand: "Jibiar",
    intensity: 3.0,
    price: 200,
    flavorNotes: ["Geleneksel Sakız", "Çam Aroması", "Mentol"],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "plombir",
    name: "Plombir",
    description:
        "Kremamsı vanilya ve hafif buzlu dokunuşlarla klasik Rus plombir dondurmasının tatlı‑ferah lezzetini yansıtan dengeli bir aroma.",
    category: "Pastane",
    tobaccoType: "Blonde",
    brand: "Jibiar",
    intensity: 3.0,
    price: 200,
    flavorNotes: ["Vanilya", "Dondurma"],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "ice_cola",
    name: "Ice Cola",
    description:
        "Klasik kola aroması, ferahlatan buz dokunuşuyla birleşiyor — tatlı, gazlı ve canlı bir içim.",
    category: "Meyveli",
    tobaccoType: "Blonde",
    brand: "Jibiar",
    intensity: 3.0,
    price: 200,
    flavorNotes: ["Klasik kola aroması", "Mentol"],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "mastır_mix",
    name: "Maser Mix",
    description:
        "21 farklı meyvenin uyumlu karışımı: yaban mersini, portakal, ahududu, çilek, şeftali, mango ve daha fazlası ile zengin ve dengeli bir meyve yolculuğu.",
    category: "Meyveli",
    tobaccoType: "Blonde",
    brand: "Jibiar",
    intensity: 3.0,
    price: 200,
    flavorNotes: [
      "Yaban Mersin,",
      "Portakal",
      "Ahududu",
      "Çilek",
      "Şeftali",
      "Mango",
    ],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
  FlavorModel(
    id: "vanilla_latte",
    name: "Vanilla Latte",
    description:
        "Kremamsı vanilya ile yumuşak latte kahve aromalarının buluştuğu, sıcak ve rahatlatıcı bir içim deneyimi.",
    category: "Pastane",
    tobaccoType: "Blonde",
    brand: "Jibiar",
    intensity: 3.0,
    price: 200,
    flavorNotes: ["Vanilya", "Latte Kahve"],
    amount: 200,
    imagePath: "lib/images/smoke.png",
  ),
];
