import 'package:hookah_menu/models/mix_model.dart';

List<MixModel> mixes = [
  MixModel(
    id: "tropical_sunrise",
    name: "Tropical Sunrise",
    description:
        "Taze mango, olgun şeftali ve tatlı-ekşi narenciye aromalarının ferahlatıcı bir karışımı.",
    ingredients: {
      "Erics Mango": 0.3,
      "Orange Team": 0.2,
      "Sweet Peach": 0.3,
      "Turbo Tea": 0.2,
    },
    intensity: 7,
    isFavorite: false,
    mixType: "Meyveli",
    mixTobaccoType: "Dark",
    mixWeight: 50,
    similarMixes: [],
  ),

  MixModel(
    id: "tropical_fusion",
    name: "Tropical Fusion",
    description:
        "Tropikal ananas, olgun şeftali ve ferah lime aromalarının enerjik karışımı.",
    ingredients: {
      "Ananas Shock": 0.4,
      "Brazilian Tea": 0.2,
      "Lemon Blast": 0.1,
      "Moon Peach": 0.3,
    },
    intensity: 6,
    isFavorite: false,
    mixType: "Meyveli",
    mixTobaccoType: "Dark",
    mixWeight: 50,
    similarMixes: [],
  ),

  MixModel(
    id: "sweet_indulgence",
    name: "Sweet Indulgence",
    description:
        "Kremamsı waffle, brownie ve karamelize fıstık aromalarının tatlı karışımı.",
    ingredients: {
      "Creamy Waffle": 0.3,
      "Brownie": 0.4,
      "Deep Blue Sea": 0.1,
      "Monkey Nuts": 0.2,
    },
    intensity: 8,
    isFavorite: false,
    mixType: "Pastane",
    mixTobaccoType: "Cigar",
    mixWeight: 50,
    similarMixes: [],
  ),

  MixModel(
    id: "tropical_harmony",
    name: "Tropical Harmony",
    description: "Tropikal mango, ananas ve çileğin dengeli karışımı.",
    ingredients: {
      "Pineapple Mango": 0.4,
      "Passion Plum": 0.2,
      "Brazilian Tea": 0.1,
      "Tropic Juice": 0.2,
      "Strawberry": 0.1,
    },
    intensity: 5,
    isFavorite: false,
    mixType: "Meyveli",
    mixTobaccoType: "Dark",
    mixWeight: 50,
    similarMixes: [],
  ),

  MixModel(
    id: "citrus_brownie",
    name: "Citrus Brownie",
    description: "Çikolata, limon ve portakalın tatlı-ferah dengesi.",
    ingredients: {
      "Brownie": 0.6,
      "Lemon Pie": 0.2,
      "Lemon": 0.1,
      "Orange Team": 0.1,
    },
    intensity: 8,
    isFavorite: false,
    mixType: "Pastane",
    mixTobaccoType: "Dark",
    mixWeight: 100,
    similarMixes: [],
  ),

  MixModel(
    id: "fruity_symphony",
    name: "Fruity Symphony",
    description: "Passion fruit, şeftali ve çileğin tropikal uyumu.",
    ingredients: {
      "Passion Fruits": 0.6,
      "Moon Peach": 0.2,
      "Strawberry": 0.1,
      "Orange Team": 0.1,
    },
    intensity: 6,
    isFavorite: false,
    mixType: "Meyveli",
    mixTobaccoType: "Dark",
    mixWeight: 100,
    similarMixes: [],
  ),

  MixModel(
    id: "exotic_paradise",
    name: "Exotic Paradise",
    description: "Egzotik meyvelerin ferah ve enerjik karışımı.",
    ingredients: {
      "Jungle Mix": 0.3,
      "Sweet Peach": 0.3,
      "Pineapple Mango": 0.3,
      "Supernova": 0.1,
    },
    intensity: 6,
    isFavorite: false,
    mixType: "Meyveli",
    mixTobaccoType: "Dark",
    mixWeight: 100,
    similarMixes: [],
  ),

  MixModel(
    id: "citrus_noir",
    name: "Citrus Noir",
    description: "Narenciye ve baharatlı aromaların güçlü uyumu.",
    ingredients: {"Citrus Mix": 0.4, "Kashmir Black": 0.4, "Pinkman": 0.2},
    intensity: 6,
    isFavorite: false,
    mixType: "Meyveli",
    mixTobaccoType: "Dark",
    mixWeight: 6,
    similarMixes: [],
  ),

  MixModel(
    id: "kremali_waffle_ruyasi",
    name: "Kremalı Waffle Rüyası",
    description: "Waffle, brownie ve pudingin tatlı uyumu.",
    ingredients: {"Brownie": 0.4, "Pudding": 0.3, "Creamy Waffle": 0.3},
    intensity: 6,
    isFavorite: false,
    mixType: "Pastane",
    mixTobaccoType: "Cigar",
    mixWeight: 6,
    similarMixes: [],
  ),

  MixModel(
    id: "plombir_dejavu_mix",
    name: "Dondurma Deja Vu",
    description: "Dondurma ve ferah meyve aromalarının hafif karışımı.",
    ingredients: {"Plombir": 0.4, "Deja Vu": 0.6},
    intensity: 3,
    isFavorite: false,
    mixType: "Pastane",
    mixTobaccoType: "Blonde",
    mixWeight: 6,
    similarMixes: [],
  ),
];
